title = "Bilinear MLPs paper spotlight at ICLR'25"
date = "2025-01-20"
description = "Our paper on weight-based interpretability was accepted as a spotlight presentation at ICLR'25!"
icon = "fa-solid fa-star"
link = "/research/bilinear"
