title = "Spotlight at the Mechanistic Interpretability workshop"
date = "2025-10-01"
description = "Our paper on bilinear autoencoders is a spotlight paper!"
icon = "fa-solid fa-star"
link = "/research/bae"
