title = "A compositional approach to interpretability"
date = "2025-10-01"
conference = "Flanders AI Day"
description = "A deep-dive session on defining interpretability"
link = "https://docs.google.com/presentation/d/1H9X0Yb2DDh4LpGCMn3yzf3_KggxJTj2su48iuE1Z1vY/edit?usp=sharing"
external = true
