title = "Embodied Language Models"
date = "2023-06-01"
conference = "University lecture"
description = "A presentation on the integration of LLMs into robotics."
link = "https://docs.google.com/presentation/d/1oURN_cmpF-GYLYVCDLU7teZ2RL_I5oeMH8onfU7ffNM/edit?usp=sharing"
external = true
