title = "Introduction to Transformers"
date = "2024-01-01"
conference = "Lab meeting"
description = "An informal introduction to the Transformer architecture."
link = "https://docs.google.com/presentation/d/1VBMEUE1bb5h48DFhSBZ8L20PJ1LwN1LMippYOZjLHos/edit?usp=sharing"
external = true
